// PakistanCraft — biome definitions
import { Block } from "./blocks";

export const Biome = {
  PUNJAB_PLAINS: 0,
  SINDH_DESERT: 1,
  THAR_DESERT: 2,
  BALOCHISTAN_MOUNTAINS: 3,
  KHYBER_FOREST: 4,
  KASHMIR_VALLEY: 5,
  GILGIT_SNOW: 6,
  ARABIAN_BEACH: 7,
  SALT_RANGE: 8,
  RIVER_BANK: 9,
  MANGROVE: 10,
  SWAT_FOREST: 11,
  POTHOHAR: 12,
} as const;

export type BiomeId = number;

export interface BiomeDef {
  id: BiomeId;
  name: string;
  nameUrdu: string;
  surface: number; // top block
  subsurface: number; // few blocks below surface
  filler: number; // deep ground
  // vegetation
  treeType: "none" | "neem" | "palm" | "mango" | "pine" | "mixed";
  treeDensity: number; // 0..1 chance per column
  cactusDensity: number;
  // surface decorations
  grassDensity: number; // tall grass / poppy
  cropDensity: number; // wheat/rice/cotton patches
  waterBlock: number;
  // climate
  temp: number; // display only
  color: string; // map color
}

export const BIOMES: Record<number, BiomeDef> = {
  [Biome.PUNJAB_PLAINS]: {
    id: Biome.PUNJAB_PLAINS,
    name: "Punjab Plains",
    nameUrdu: "پنجاب کے میدان",
    surface: Block.GRASS,
    subsurface: Block.DIRT,
    filler: Block.STONE,
    treeType: "neem",
    treeDensity: 0.02,
    cactusDensity: 0,
    grassDensity: 0.18,
    cropDensity: 0.04,
    waterBlock: Block.WATER,
    temp: 0.7,
    color: "#4f8a3a",
  },
  [Biome.SINDH_DESERT]: {
    id: Biome.SINDH_DESERT,
    name: "Sindh Desert",
    nameUrdu: "سندھ کا صحرا",
    surface: Block.SAND,
    subsurface: Block.SAND,
    filler: Block.SANDSTONE,
    treeType: "palm",
    treeDensity: 0.008,
    cactusDensity: 0.04,
    grassDensity: 0,
    cropDensity: 0,
    waterBlock: Block.WATER,
    temp: 0.95,
    color: "#e0c878",
  },
  [Biome.THAR_DESERT]: {
    id: Biome.THAR_DESERT,
    name: "Thar Desert",
    nameUrdu: "تھر کا صحرا",
    surface: Block.SAND,
    subsurface: Block.SAND,
    filler: Block.SANDSTONE,
    treeType: "palm",
    treeDensity: 0.005,
    cactusDensity: 0.06,
    grassDensity: 0,
    cropDensity: 0,
    waterBlock: Block.WATER,
    temp: 1.0,
    color: "#d9b85a",
  },
  [Biome.BALOCHISTAN_MOUNTAINS]: {
    id: Biome.BALOCHISTAN_MOUNTAINS,
    name: "Balochistan Mountains",
    nameUrdu: "بلوچستان کے پہاڑ",
    surface: Block.STONE,
    subsurface: Block.STONE,
    filler: Block.STONE,
    treeType: "none",
    treeDensity: 0,
    cactusDensity: 0,
    grassDensity: 0.02,
    cropDensity: 0,
    waterBlock: Block.WATER,
    temp: 0.5,
    color: "#7d7d7d",
  },
  [Biome.KHYBER_FOREST]: {
    id: Biome.KHYBER_FOREST,
    name: "Khyber Forest",
    nameUrdu: "خیبر کا جنگل",
    surface: Block.GRASS,
    subsurface: Block.DIRT,
    filler: Block.STONE,
    treeType: "pine",
    treeDensity: 0.08,
    cactusDensity: 0,
    grassDensity: 0.1,
    cropDensity: 0,
    waterBlock: Block.WATER,
    temp: 0.45,
    color: "#2f5a22",
  },
  [Biome.KASHMIR_VALLEY]: {
    id: Biome.KASHMIR_VALLEY,
    name: "Kashmir Valley",
    nameUrdu: "کشمیر کی وادی",
    surface: Block.GRASS,
    subsurface: Block.DIRT,
    filler: Block.STONE,
    treeType: "mixed",
    treeDensity: 0.05,
    cactusDensity: 0,
    grassDensity: 0.14,
    cropDensity: 0.02,
    waterBlock: Block.WATER,
    temp: 0.4,
    color: "#3f6b2c",
  },
  [Biome.GILGIT_SNOW]: {
    id: Biome.GILGIT_SNOW,
    name: "Gilgit Snow Peaks",
    nameUrdu: "گلگت کی برفانی چوٹیاں",
    surface: Block.SNOW,
    subsurface: Block.STONE,
    filler: Block.STONE,
    treeType: "none",
    treeDensity: 0,
    cactusDensity: 0,
    grassDensity: 0,
    cropDensity: 0,
    waterBlock: Block.ICE,
    temp: 0.05,
    color: "#f5f7fa",
  },
  [Biome.ARABIAN_BEACH]: {
    id: Biome.ARABIAN_BEACH,
    name: "Arabian Sea Beach",
    nameUrdu: "بحیرہ عرب کا ساحل",
    surface: Block.SAND,
    subsurface: Block.SAND,
    filler: Block.SANDSTONE,
    treeType: "palm",
    treeDensity: 0.01,
    cactusDensity: 0,
    grassDensity: 0,
    cropDensity: 0,
    waterBlock: Block.WATER,
    temp: 0.85,
    color: "#d9c178",
  },
  [Biome.SALT_RANGE]: {
    id: Biome.SALT_RANGE,
    name: "Salt Range",
    nameUrdu: "سلٹ رینج",
    surface: Block.STONE,
    subsurface: Block.STONE,
    filler: Block.STONE,
    treeType: "none",
    treeDensity: 0.005,
    cactusDensity: 0,
    grassDensity: 0.02,
    cropDensity: 0,
    waterBlock: Block.WATER,
    temp: 0.6,
    color: "#e8e0d0",
  },
  [Biome.RIVER_BANK]: {
    id: Biome.RIVER_BANK,
    name: "Indus River Bank",
    nameUrdu: "دریائے سندھ کا کنارہ",
    surface: Block.SAND,
    subsurface: Block.DIRT,
    filler: Block.STONE,
    treeType: "neem",
    treeDensity: 0.01,
    cactusDensity: 0,
    grassDensity: 0.08,
    cropDensity: 0.06,
    waterBlock: Block.WATER,
    temp: 0.7,
    color: "#c9a85a",
  },
  [Biome.MANGROVE]: {
    id: Biome.MANGROVE,
    name: "Mangrove Coast",
    nameUrdu: "مینگروو ساحل",
    surface: Block.CLAY,
    subsurface: Block.CLAY,
    filler: Block.STONE,
    treeType: "palm",
    treeDensity: 0.04,
    cactusDensity: 0,
    grassDensity: 0.05,
    cropDensity: 0,
    waterBlock: Block.WATER,
    temp: 0.9,
    color: "#b0a890",
  },
  [Biome.SWAT_FOREST]: {
    id: Biome.SWAT_FOREST,
    name: "Swat Forest",
    nameUrdu: "سوات کا جنگل",
    surface: Block.GRASS,
    subsurface: Block.DIRT,
    filler: Block.STONE,
    treeType: "pine",
    treeDensity: 0.1,
    cactusDensity: 0,
    grassDensity: 0.12,
    cropDensity: 0,
    waterBlock: Block.WATER,
    temp: 0.4,
    color: "#2c5a1c",
  },
  [Biome.POTHOHAR]: {
    id: Biome.POTHOHAR,
    name: "Potohar Plateau",
    nameUrdu: "پوٹھوہار کا سطح مرتفع",
    surface: Block.GRASS_DRY,
    subsurface: Block.DIRT,
    filler: Block.STONE,
    treeType: "neem",
    treeDensity: 0.015,
    cactusDensity: 0.01,
    grassDensity: 0.08,
    cropDensity: 0.02,
    waterBlock: Block.WATER,
    temp: 0.65,
    color: "#b09040",
  },
};

export function getBiome(id: BiomeId): BiomeDef {
  return BIOMES[id] || BIOMES[Biome.PUNJAB_PLAINS];
}
